export const GET_MOVIE_CONFIG = 'GET_MOVIE_CONFIG';

export const GET_TRENDING_MOVIES_START = 'GET_TRENDING_MOVIES_START';
export const GET_TRENDING_MOVIES_SUCCESS = 'GET_TRENDING_MOVIES_SUCCESS';
export const GET_TRENDING_MOVIES_FAILURE = 'GET_TRENDING_MOVIES_FAILURE';