export const GET_MOVIE_CONFIG = 'GET_MOVIE_CONFIG';

export const GET_TRENDING_MOVIES_START = 'GET_TRENDING_MOVIES_START';
export const GET_TRENDING_MOVIES_SUCCESS = 'GET_TRENDING_MOVIES_SUCCESS';
export const GET_TRENDING_MOVIES_FAILURE = 'GET_TRENDING_MOVIES_FAILURE';

export const GET_MOVIE_GENRES_START = 'GET_MOVIE_GENRES_START';
export const GET_MOVIE_GENRES_SUCCESS = 'GET_MOVIE_GENRES_SUCCESS';
export const GET_MOVIE_GENRES_FAILURE = 'GET_MOVIE_GENRES_FAILURE';

export const GET_NOW_PLAYING_START = 'GET_NOW_PLAYING_START';
export const GET_NOW_PLAYING_SUCCESS = 'GET_NOW_PLAYING_SUCCESS';
export const GET_NOW_PLAYING_FAILURE = 'GET_NOW_PLAYING_FAILURE';